CEN_Library_Project/CEN_Library_Project/urls.py
from django.contrib import admin

from django.urls import path, include  # , re_path  # re_path ADDED FOR ANGULAR
from django.conf import settings

from django.conf.urls.static import static, serve  # serve added FOR ANGULAR
from rest_framework.routers import DefaultRouter

import onlinelibrary.api_views

urlpatterns = [
    path('', include('onlinelibrary.urls')),
    path('admin/', admin.site.urls),

    #  REGISTER APP  # this goes to django.contrib.auth.urls application, it will look
    # in the url file there and will see if we have a valid url, so it will se if we have something like "login"
    # "logout "change-password" "create-password" etc. So what we need to do is create a registration folder called
    # registration and put login.html in there because that is where django is going to look and what template we will
    # use to render our login form.


    #  Register URL
    path('register/', include("register.urls")),
    path('', include("django.contrib.auth.urls")),


    #  CART APP URLS:
    path('ShoppingCart/', include("cart.urls")),  # this connects to the urls.py inside the app cart

    #  WISHLIST APP URLS:
    path('wishlist/', include("wishlist.urls")),  # this connects to the urls.py inside the app wishlist

    # ONLINELIBRARY APP URLS
    path('', include("onlinelibrary.urls")),  # this connects to the urls.py inside the app onlinelibrary

    #  RATINGREVIEW APP URLS:
    path('ratingReview/', include("ratingReview.urls")),  # this connects to the urls.py inside the app ratingReview

    #  RESTful API VIEWS FOR SHOPPINGCARTITEMS
    path('api/v1/shoppingcartitems/', onlinelibrary.api_views.ShoppingCartItemList.as_view()),  # This is for the
    # RESTful api views for the shoppingcartapi
    path('api/v1/shoppingcartitems/new', onlinelibrary.api_views.ShoppingCartItemCreate.as_view()),  # This is for the
    # RESTful api views for the shoppingcartapi
    path('api/v1/shoppingcartitems/<int:id>/',  # This is for the  RESTful api views for the shoppingcartapi
         onlinelibrary.api_views.ShoppingCartItemRetriveUpdateDestroy.as_view()),  # This is for the  RESTful api views
    # for the shoppingcartapi


    path('bookdetails/', include('bookdetails.urls')),

    #Browse/Sort/Search URLS
    path('browse/', include('browse.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CEN_Library_Project/cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path("delete/<int:cartitemid>", views.delete_cart_item, name="deletecartitem"),  # this connects to the
    # views in cart app
    path("sfl/<int:cartitemid>", views.save_for_later, name="saveforlater"),  # this connects to the
    # views in cart app
    path("mtc/<int:cartitemid>", views.move_to_cart, name="movetocart"),  # this connects to the
    # views in cart app
    path("updateqnty/<int:cartitemid>", views.update_quantity, name="updateqty"),
    path("checkout", views.checkout, name="checkout"),# this connects to the
    # views in cart app
    path('', views.shoppingcartview, name='cart'),  # this connects to the
    # views in cart app
]

CEN_Library_Project/wishlist/urls.py
from django.urls import path
from wishlist import views

urlpatterns = [
    path("", views.wishlist, name="wishlist"),
    path("<int:id>", views.index, name="indexwl"),
    path("delete/<int:id>", views.delete_wishlist, name="delete_wishlist"),
    path("remove/<int:id>", views.remove_book, name="remove_book"),
    path("transfer/<int:bookid>", views.move_book, name="move_book"),
    path("movetocart/<int:bookid>", views.move_to_cart, name="move_to_cart"),
    path("transferbook/<int:fromwishlistid>/<int:towishlistid>/<int:bookid>", views.transfer_book, name="transfer_book"),
    path("addbooktowishlist/<int:towishlistid>/<int:bookid>", views.add_book_to_wishlist, name="add_book_to_wishlist"),
    path("setprimary/<int:wishlistid>", views.set_primary, name="set_primary"),
    path("removeprimary/", views.remove_primary, name="remove_primary"),
]

CEN_Library_Project/bookdetails/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db.models import Avg
from decimal import Decimal


class Author(models.Model):
    author = models.CharField(max_length=200)
    bio = models.CharField(max_length=4000)

    class Meta:
        ordering = ['author']

    def __str__(self):
        return self.author


class Book(models.Model):

    authors = models.ManyToManyField(
        Author,
        related_name='booker',
    )

    GENRES = (
        ('Sci-fi', 'Sci-fi'),
        ('Fantasy', 'Fantasy'),
        ('Children', 'Children'),
        ('Non-fiction', 'Non-fiction'),
        ('Others', 'Others'),
    )

    cover = models.ImageField(upload_to='bookImages', default='bookImages/No_image.jpg')
    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=200, default='other', choices=GENRES)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    description = models.CharField(max_length=4000)
    publisher = models.CharField(max_length=200, default='Unknown')
    release_date = models.DateField(default='Unknown')
    bestseller = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def average_rating(self):
        average = self.ratings.all().aggregate(Avg('rating')).get('rating__avg') or 0.0
        if average is not None:
            Decimal(average)
        return round(average, 1)


# Rating and Review Portion
class RatingReview(models.Model):
    RATE = (
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    )
    book = models.ForeignKey("Book", on_delete=models.CASCADE, default=0, related_name="ratings")
    rating = models.CharField(choices=RATE, max_length=128, default=1)
    review = models.CharField(max_length=128, default='Write Review')
    username = models.CharField(max_length=128, default="")
    nickName = models.BooleanField(default=False)
    first_name = models.CharField(max_length=128, default="")
    last_name = models.CharField(max_length=128, default="")
    book_title = models.CharField(max_length=128, default="")
    anonymous = models.BooleanField(default=False)
    anony = models.BooleanField(default=False)


    def str(self):
        return self.rating

    class Meta:
        managed = True
        db_table = 'ratingReview_bookdetails'

CEN_Library_Project/wishlist/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from bookdetails.models import Book


# Create your models here.

class WishList(models.Model):
    name = models.CharField(max_length=200)
    primary = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wishlist", null=True)
    book = models.ManyToManyField(Book, related_name="bookwish")

    def __str__(self):
        return self.name

    def getuserid(self):
        return self.user.id

    def getbookid(self):
        return self.book

CEN_Library_Project/WishList/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import WishList, Book


# Create your views here.

def index(response, id):
    ls = WishList.objects.get(id=id)
    return render(response, "onlinelibrary/List.html", {"ls": ls})

def wishlist(response):
    wl = WishList.objects.all()

    if response.method == "POST":
        print(response.POST)
        if response.POST.get("new"):
            txt = response.POST.get("new")
            if len(txt) > 2:
                wl.create(name=txt, primary=False)
            else:
                print("invalid")

    return render(response, "onlinelibrary/WishListHome.html", {"wl": wl})

CEN_Library_Project/wishlist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from .models import WishList
from register.models import Profile
from bookdetails.models import Book
from cart.models import ShoppingCart
from cart.models import ShoppingCartItem

# Create your views here.


def index(response, id):  # good to go
    wl = WishList.objects.get(id=id)
    global wishlist_id
    wishlist_id = id
    bk = wl.book.all()
    return render(response, "wishlist/list.html", {"wl":wl, "bk": bk})


def wishlist(response):  # good to go
    wl = WishList.objects.filter(user=response.user)
    counter = 0
    counter2 = 0

    if response.method == "POST":
        print(response.POST)
        if response.POST.get("new"):
            txt = response.POST.get("new")
            if len(txt) > 2:
                if response.user.profile.wishlistCounter < 3:
                    response.user.profile.addWishlist()
                    response.user.profile.save()
                    wl.create(name=txt, primary=False, user=response.user)
                    return redirect('/wishlist/')
                else:
                    message = "Oops! You cannot have more than 3 wish lists."
                    for i in message:
                        counter += 1
                    return render(response, "wishlist/wishlisthome.html", {"wl": wl, "counter": counter, "message": message})
                    raise Exception("Maximum number of List")
            else:
                message2 = "Oops! The name for your list is too short, it must contain at least 3 letters."
                for i in message2:
                    counter2 += 1
                return render(response, "wishlist/wishlisthome.html",
                              {"wl": wl, "counter2": counter2, "message2": message2})
                raise Exception("Invalid Name")

    return render(response, "wishlist/wishlisthome.html", {"wl": wl})


def set_primary(request, wishlistid):
    wl = WishList.objects.filter(user=request.user)

    if request.method == 'POST':
        userlists = WishList.objects.all()
        for l in userlists:
            if l.user == request.user and l.primary:
                l.primary = False
                l.save()
        setprimarywishlist = WishList.objects.get(id=wishlistid)
        setprimarywishlist.primary = True
        setprimarywishlist.save()
        wl = WishList.objects.filter(user=request.user)
        return render(request, "wishlist/wishlisthome.html", {"wl": wl})

    else:
        return render(request, "wishlist/wishlisthome.html", {"wl": wl})


def remove_primary(request):
    wl = WishList.objects.filter(user=request.user)

    if request.method == 'POST':
        userlists = WishList.objects.all()
        for l in userlists:
            if l.user == request.user and l.primary:
                l.primary = False
                l.save()
        wl = WishList.objects.filter(user=request.user)
        return render(request, "wishlist/wishlisthome.html", {"wl": wl})

    else:
        return render(request, "wishlist/wishlisthome.html", {"wl": wl})


def delete_wishlist(request, id):  # good to go
    wl = WishList.objects.get(id=id)
    if request.method == "POST":
        wl.delete()
        request.user.profile.wishlistCounter = request.user.profile.wishlistCounter - 1
        request.user.profile.save()
        return redirect('/wishlist/')

    return render(request, "wishlist/delete.html", {'wl': wl})


def remove_book(request, id):  # good to go
    wl = WishList.objects.get(id=wishlist_id)
    bk = wl.book.get(id=id)
    if request.method == "POST":
        wl.book.remove(bk)
        return redirect('indexwl', wl.id)

    return render(request, 'wishlist/remove.html', {"bk": bk, "wl": wl})


def move_book(request, id):
    wl = WishList.objects.get(id=wishlist_id)
    bk = wl.book.get(id=id)
    if request.method == "POST":
        wl.book.id = wishlist_id
        return redirect('/wishlist/')

    return render(request, 'wishlist/transfer.html', {"bk": bk})


def move_to_cart(response, bookid):
    userid = response.user.id
    wl = WishList.objects.get(id=wishlist_id)
    bk = Book.objects.get(id=bookid)
    cart = ShoppingCart.objects.get(id=userid)

    # for every shoppingcartitem in the cart object of the user
    for item in cart.shoppingcartitem_set.all():
        #  if the item is not marked as ordered and the book saved in the shoppingcartitem object
        # is the same book that we are moving from wishlist
        if item.ordered == False and item.book == bk:
            item.quantity = item.quantity + 1  # Update the quantity of that shippingcartitem
            if item.savedforlater: #  if the shoppingcartitem object that holds the book being moved is in the
                # saved for later section of the shopping cart
                item.savedforlater = False #  take it out of the saved for later section and move it to the main
                # section of the shopping cart
            item.save()
            cart.save()
            wl.book.remove(bk)
            return redirect('indexwl', wl.id)
    cartitem = ShoppingCartItem.objects.all()
    cartitem.create(shoppingcart=cart, book=bk, quantity=1, ordered=False, savedforlater=False)
    wl.book.remove(bk)
    return redirect('indexwl', wl.id)


def transfer_book(request, fromwishlistid, towishlistid, bookid):
    userid = request.user.id
    allWishLists = WishList.objects.all()
    wl = WishList.objects.get(id=fromwishlistid)
    tolist = WishList.objects.get(id=towishlistid)
    bk = Book.objects.get(id=bookid)

    if request.method == 'POST':
        wl.book.remove(bk)
        tolist.book.add(bk)
        wl.save()
        tolist.save()
        return redirect('indexwl', tolist.id)

    return render(request, 'wishlist/transfer_book.html', {"allWishLists": allWishLists, "wl": wl, "bk": bk})


def add_book_to_wishlist(request, towishlistid, bookid):
    userid = request.user.id
    allWishLists = WishList.objects.all()
    bk = Book.objects.get(id=bookid)

    if request.method == 'POST':
        tolist = WishList.objects.get(id=towishlistid)
        tolist.book.add(bk)
        tolist.save()
        return redirect('indexwl', tolist.id)

    return render(request, 'wishlist/add_book_to_wishlist.html', {"allWishLists": allWishLists, "bk": bk})

CEN_Library_Project/wishlist/templates/wishlist/List.html
{% extends 'wishlist/base.html' %}
{% block title %}View Wish List {% endblock %}

{% block content %}
    <h1>{{ls.name}}</h1>
    <ul>
    {% for book in ls.book_set.all %}
        {% if book.added == True %}
        <li>{{book.name}}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% endblock %}

CEN_Library_Project/wishlist/templates/wishlist/WishListHome.html
{% extends 'wishlist/base.html' %}

{% block title%}
Wish List
{% endblock%}

{% block content%}
<h1>Wish Lists Home Page</h1>


<script>
    angular.module('checkboxExample', [])
        .controller('ExampleController', ['$scope', function ($scope) {
            $scope.checkboxModel = {
                value1: true
            };
        }]);
</script>
<form  method="post" action="#">


    <button type="submit" , name="new" , value="new">Create New</button>
    <input type="text", name="new">
    {% csrf_token %}
    <ul>
        {% for wl in wl %}
        <table>
            <h1><a href="http://127.0.0.1:8000/wishlist/{{wl.id}}"> {{wl.name}}</a></h1>
            {% if wl.primary == True %}
            <li><input type="checkbox", value="true", name="{{wl.id}}" checked>Primary</li>
            {% else %}
            <li><input type="checkbox", value="true", name="{{wl.id}}">Primary</li>
            {% endif %}
            <button type="submit" , name="delete" , value="delete">Delete</button>

        </table>
        {% endfor %}

    </ul>
</form>
{% endblock%}

CEN_Library_Project/wishlist/templates/wishlist/add_book_to_wishlist.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Add Book to Wishlist
{% endblock%}

{% block content %}
<p>Are you sure you want to move "{{bk.title}}"?</p>
<button onclick="window.location.href='http://127.0.0.1:8000/bookdetails/{{bk.id}}';" type="button" class="btn btn-danger">Cancel</button>
    {% for list in allWishLists %}
        {% if list.user == user %}
            <br>
            <br>
            <form action="{% url 'add_book_to_wishlist' list.id bk.id %}" method="POST">
                {% csrf_token %}
                <button type="submit", name="Confirm", class="btn btn-success", value="new">Add to {{list.name}} </button>
            </form>
        {% endif %}
    {% endfor %}
{% endblock%}

CEN_Library_Project/wishlist/templates/wishlist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Wish List Home{% endblock %}</title>
</head>
<body>
<div id="content", name="content">
    {% block content%}
    {% endblock%}
</div>
</body>
</html>

CEN_Library_Project/wishlist/templates/wishlist/delete.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Delete
{% endblock%}

{% block content%}
<div class="information">
    <p>Are you sure you want to delete "{{wl.name}}"?</p>
    <button onclick="window.location.href='http://127.0.0.1:8000/wishlist';" type="button" class="btn btn-danger">Cancel</button>
    <br>
    <br>

    <form action="{% url 'delete_wishlist' wl.id %}" method="POST">
        {% csrf_token %}
        <button type="submit", name="Confirm", class="btn btn-success", value="new">Submit</button>
    </form>
</div>

{% endblock %}

CEN_Library_Project/wishlist/templates/wishlist/list.html
{% extends 'onlinelibrary/base.html' %}

{% block title %} {{ls.name}} {% endblock %}

{% block content %}
<br>
<button onclick="window.location.href='http://127.0.0.1:8000/wishlist';" type="button" class="btn btn-primary">
    Back to Wish Lists
</button>
<br>
<br>
    <h1>{{wl.name}}</h1>
    <br>
    <ul>
       <table class="table">
            <thead>
                <tr>
                    <th>Cover</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Genre</th>
                    <th>Rating</th>
                    <th>Price</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
        {% for book in bk %}
            <tr>

                <td>
                    <button onclick="window.location.href='http://127.0.0.1:8000/bookdetails/{{book.id}}';" type="button" >
                        <img src="{{book.cover.url}}" alt="" width="100" height="100">
                    </button>
                </td>
                <td>
                    <button onclick="window.location.href='http://127.0.0.1:8000/bookdetails/{{book.id}}';" type="button" class="btn btn-secondary">
                        {{book.title}}
                    </button>
                </td>
                <td>
                    {% for autor in book.authors.all %}
                        {{autor}}
                        <br>
                    {% endfor %}
                </td>
                <td>{{book.genre}}</a></td>
                <td>{{book.average_rating}}</a></td>
                <td>{{book.price}}</a></td>
                <td>
                    <form action="{% url 'move_to_cart' book.id%}" method="POST">
                        {% csrf_token %}
                        <button type="submit", name="MoveToCart", class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                            </svg>
                        </button>
                    </form>
                </td>
                <td>
                    <!-- TODO: Editing -->
                    <button onclick="window.location.href='transferbook/{{wl.id}}/{{wl.id}}/{{book.id}}';" type="button" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder-symlink" viewBox="0 0 16 16">
                            <path d="M11.798 8.271l-3.182 1.97c-.27.166-.616-.036-.616-.372V9.1s-2.571-.3-4 2.4c.571-4.8 3.143-4.8 4-4.8v-.769c0-.336.346-.538.616-.371l3.182 1.969c.27.166.27.576 0 .742z"/>
                            <path d="M.5 3l.04.87a1.99 1.99 0 0 0-.342 1.311l.637 7A2 2 0 0 0 2.826 14h10.348a2 2 0 0 0 1.991-1.819l.637-7A2 2 0 0 0 13.81 3H9.828a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 6.172 1H2.5a2 2 0 0 0-2 2zm.694 2.09A1 1 0 0 1 2.19 4h11.62a1 1 0 0 1 .996 1.09l-.636 7a1 1 0 0 1-.996.91H2.826a1 1 0 0 1-.995-.91l-.637-7zM6.172 2a1 1 0 0 1 .707.293L7.586 3H2.19c-.24 0-.47.042-.684.12L1.5 2.98a1 1 0 0 1 1-.98h3.672z"/>
                        </svg>
                        Tansfer
                    </button>
                    <!-- TODO: End Editing -->
                </td>
                <td>
                    <button onclick="window.location.href='remove/{{book.id}}';" type="button" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </button>
                </td>
            </tr>
        {% endfor %}
       </table>
    </ul>
{% endblock %}

CEN_Library_Project/wishlist/templates/wishlist/remove.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Remove
{% endblock%}

{% block content%}

<p>Are you sure you want to delete "{{bk.title}}" from your Wish List?</p>
<button onclick="window.location.href='http://127.0.0.1:8000/wishlist/{{wl.id}}';" type="button" class="btn btn-danger">Cancel</button>
<br>
<br>

<form action="{% url 'remove_book' bk.id %}" method="POST">
    {% csrf_token %}
    <button type="submit", name="Confirm", class="btn btn-success", value="new">Submit</button>
</form>

{% endblock %}

CEN_Library_Project/wishlist/templates/wishlist/transfer.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Delete
{% endblock%}

{% block content%}

<p>Are you sure you want to delete "{{wl.name}}"?</p>

<form action="{% url 'delete_wishlist' wl.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'wishlist' %}">Cancel</a>
    <button type="submit", name="Confirm", class="btn btn-success", value="new">Submit</button>
</form>

{% endblock %}

CEN_Library_Project/wishlist/templates/wishlist/transfer_book.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Transfer Book
{% endblock%}

{% block content %}
<p>Are you sure you want to move "{{bk.title}}"?</p>
<button onclick="window.location.href='http://127.0.0.1:8000/wishlist/{{wl.id}}';" type="button" class="btn btn-danger">Cancel</button>
<br>
<br>
    {% for list in allWishLists %}
        {% if list.user == user and list.id != wl.id%}
            <form action="{% url 'transfer_book' wl.id list.id bk.id %}" method="POST">
                {% csrf_token %}
                <button type="submit", name="Confirm", class="btn btn-success", value="new">Move to {{list.name}} </button>
            </form>
            <br>
        {% endif %}
    {% endfor %}
{% endblock%}

CEN_Library_Project/wishlist/templates/wishlist/wishlisthome.html
{% extends 'onlinelibrary/base.html' %}

{% block title%}
Wish List
{% endblock%}

{% block content%}
{% if counter > 0 %}
<div class="alert alert-danger" role="alert">
    {{message}}
</div>
{% endif %}
{% if counter2 > 0 %}
<div class="alert alert-danger" role="alert">
    {{message2}}
</div>
{% endif %}
<h1>Wish Lists:</h1>

<form  action="http://127.0.0.1:8000/wishlist/" method="post">
{% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <button type="submit", name="new", class="btn btn-success", value="new">
                <svg class="bi bi-plus-square" fill="currentColor" height="20" viewBox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>New WishList
            </button>
        </div>
        <input name="new" type="text">
    </div>
</form>
<table class="table">
    <thead>
            <th>Name</th>
            <th>Primary</th>
            <th></th>
            <th></th>
    </thead>
        {% for list in wl %}
        <tr>
            <td>
                <button onclick="window.location.href='http://127.0.0.1:8000/wishlist/{{list.id}}';" type="button" class="btn btn-primary">
                    {{list.name}}
                </button>
                {% if list.primary == True %}
                    <button type="button" class="btn btn-danger">Primary</button>
                {% endif %}
            </td>
            <td>
                {% if list.primary == False %}
                <form action="{% url 'set_primary' list.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit", name="Confirm", class="btn btn-success", value="new">Set as Primary</button>
                </form>
                {% endif %}
                {% if list.primary == True %}
                <form action="{% url 'remove_primary' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit", name="Confirm", class="btn btn-danger", value="new">Remove Primary</button>
                </form>
                {% endif %}
            </td>
            <td>
                <button class="btn btn-danger" onclick="window.location.href='http://127.0.0.1:8000/wishlist/delete/{{list.id}}';" type="button">
                    <svg class="bi bi-trash" fill="currentColor" height="20" viewBox="0 0 16 16" width="20" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" fill-rule="evenodd"/>
                    </svg>
                </button>
            </td>
        </tr>
        {% endfor %}
</table>

{% endblock%}