CEN_Library_Project/CEN_Library_Project/urls.py
from django.contrib import admin

from django.urls import path, include  # , re_path  # re_path ADDED FOR ANGULAR
from django.conf import settings

from django.conf.urls.static import static, serve  # serve added FOR ANGULAR
from rest_framework.routers import DefaultRouter

import onlinelibrary.api_views

urlpatterns = [
    path('', include('onlinelibrary.urls')),
    path('admin/', admin.site.urls),

    #  REGISTER APP  # this goes to django.contrib.auth.urls application, it will look
    # in the url file there and will see if we have a valid url, so it will se if we have something like "login"
    # "logout "change-password" "create-password" etc. So what we need to do is create a registration folder called
    # registration and put login.html in there because that is where django is going to look and what template we will
    # use to render our login form.


    #  Register URL
    path('register/', include("register.urls")),
    path('', include("django.contrib.auth.urls")),


    #  CART APP URLS:
    path('ShoppingCart/', include("cart.urls")),  # this connects to the urls.py inside the app cart

    #  WISHLIST APP URLS:
    path('wishlist/', include("wishlist.urls")),  # this connects to the urls.py inside the app wishlist

    # ONLINELIBRARY APP URLS
    path('', include("onlinelibrary.urls")),  # this connects to the urls.py inside the app onlinelibrary

    #  RATINGREVIEW APP URLS:
    path('ratingReview/', include("ratingReview.urls")),  # this connects to the urls.py inside the app ratingReview

    #  RESTful API VIEWS FOR SHOPPINGCARTITEMS
    path('api/v1/shoppingcartitems/', onlinelibrary.api_views.ShoppingCartItemList.as_view()),  # This is for the
    # RESTful api views for the shoppingcartapi
    path('api/v1/shoppingcartitems/new', onlinelibrary.api_views.ShoppingCartItemCreate.as_view()),  # This is for the
    # RESTful api views for the shoppingcartapi
    path('api/v1/shoppingcartitems/<int:id>/',  # This is for the  RESTful api views for the shoppingcartapi
         onlinelibrary.api_views.ShoppingCartItemRetriveUpdateDestroy.as_view()),  # This is for the  RESTful api views
    # for the shoppingcartapi


    path('bookdetails/', include('bookdetails.urls')),

    #Browse/Sort/Search URLS
    path('browse/', include('browse.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CEN_Library_Project/cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path("delete/<int:cartitemid>", views.delete_cart_item, name="deletecartitem"),  # this connects to the
    # views in cart app
    path("sfl/<int:cartitemid>", views.save_for_later, name="saveforlater"),  # this connects to the
    # views in cart app
    path("mtc/<int:cartitemid>", views.move_to_cart, name="movetocart"),  # this connects to the
    # views in cart app
    path("updateqnty/<int:cartitemid>", views.update_quantity, name="updateqty"),
    path("checkout", views.checkout, name="checkout"),# this connects to the
    # views in cart app
    path('', views.shoppingcartview, name='cart'),  # this connects to the
    # views in cart app
]

CEN_Library_Project/ratingReview/urls.py
from django.shortcuts import render
from django.http import HttpResponse
from . import views
from django.urls import path

# Create your views here.

urlpatterns = [
    path("", views.rating_create_view, name='rating'),
]

CEN_Library_Project/ratingReview/models.py
from django.db import models
from django.conf import settings
from django import forms
from django.contrib.auth.models import User
from cart.models import ShoppingCart


class BookRating(models.Model):

    # book = models.ForeignKey("bookdetails.Book", on_delete=models.CASCADE, default=0, related_name="ratings")


    RATE = (
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    )

    rating = models.CharField(choices=RATE, max_length=128, default = 1)
    review = models.CharField(max_length=128, default='Write Review')
    username = models.CharField(max_length=128, default="")

    def __str__(self):
        return self.rating

    class Meta:
        managed = True
        db_table = 'ratingReview_bookrating'

CEN_Library_Project/ratingReview/forms.py
from typing import Any

from django import forms
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple, Textarea
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import BookRating
from bookdetails.models import RatingReview

RATE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
     )
class RatingForm(forms.ModelForm):

    class Meta:
        model = RatingReview
        fields = [
            'rating',
            'username',
            'review',
            'book',
            'nickName',
            'first_name',
            'last_name',
            'book_title'
        ]
        widgets = {'rating' : forms.RadioSelect, 'review' : Textarea, 'book' : Textarea}

CEN_Library_Project/ratingReview/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import BookRating
from .forms import RatingForm
from django.contrib.auth.decorators import login_required
from .models import BookRating
from cart.models import ShoppingCart


# Create your views here.
# def rating_create_view(request):
#     rating = BookRating.objects.all()
#     username = BookRating.objects.all()
#     form = RatingForm(request.POST)
#     cartitems = request.user.ShoppingCart_shoppingcartitem.all()
#     context = {
#         'form': form,
#         'rating': rating,
#         'username': username
#     }
#     counter = 0
#     if form.is_valid():
#         for book in cartitems:
#             counter = counter + 1
#         if counter > 0:
#             form.save()
#         else:
#             return render(request, "home.html", context)
#
#     return render(request, "home.html", context)


def rating_create_view(request):
    rating = BookRating.objects.all()
    username = BookRating.objects.all()
    form = RatingForm(request.POST)
    if form.is_valid():
        form.save()

    context = {
        'form': form,
        'rating': rating,
        'username': username
    }
    return render(request, "home.html", context)

CEN_Library_Project/ratingReview/templates/home.html
{%  extends 'onlinelibrary/base.html' %}

<html lang="en">
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}" />

    <link href="{% static 'ratingReview/ratingStyle.css' %}" rel="stylesheet">
    <script src="{% static 'ratingReview/rating.js' %}" type="text/javascript"></script>
    <title>Rating</title>
</head>

<body>
{% for q in username %}
    {% if q.username == user.get_username %}
        <script>
            window.onload = function EndClick() {
            var x = document.getElementById("ReviewButton");
            x.style.display = "none";
            }
        </script>




    {% endif %}
{% endfor %}

<button type="button" onclick="OnClick()" id = "ReviewButton">Try it</button>
<form  method="POST" action="{% url 'rating' %}"class = "rating" id = 'ratingForm'>

    <span class = "left">
    <label for="id_rating_0"></label><span id="id_rating">
    <label for="id_rating_0" class = "fas fa-star" ></label>
    <input type="radio" name="rating"value="1" required="" id="id_rating_0">

    <label for="id_rating_1" class = "fas fa-star" ></label>
    <input type="radio" name="rating"value="2" required="" id="id_rating_1">

    <label for="id_rating_2" class = "fas fa-star" ></label>
    <input type="radio" name="rating"value="3" required="" id="id_rating_2">

    <label for="id_rating_3" class = "fas fa-star" ></label>
    <input type="radio" name="rating"value="4" required="" id="id_rating_3">

    <label for="id_rating_4" class = "fas fa-star" ></label>
    <input type="radio" name="rating"value="5" required="" id="id_rating_4">
    </span>

    <input type="hidden" name="csrfmiddlewaretoken" value="ze08sScoVTW1a8SSefw4Ek9lWIL24fc5mRf4biq62tigEzkRIg9oSMrLOLIIKK47">

<label for="id_username"></label><input type="text" name="username" value="{{user.get_username}}" maxlength="128" required="" id="id_username" hidden>
<label for="id_review">Review:</label><textarea name="review" cols="40" rows="10" maxlength="128" required="" id="id_review">Hello</textarea>
    <input type="submit" value="submit" onclick="OnClick()">
</form>
</body>

<body class = "PastRatings">
    {% for q in username %}
    <div>{{q.username}}</div>

    {% if q.rating == "5" %}
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    {% endif %}

    {% if q.rating == "4" %}
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star"></p>
    {% endif %}

    {% if q.rating == "3" %}
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    {% endif %}

    {% if q.rating == "2" %}
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    {% endif %}

    {% if q.rating == "1" %}
    <p class = "fas fa-star" style = "color: #fd4"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    <p class = "fas fa-star"></p>
    {% endif %}

    <div>{{q.review}}</div>
    <br>
    {% endfor %}
</body>
<script>
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>
{% endblock %}
</html>